feat: term preview
Flouse/ckb-academy pull request #34
Opened 2023-04-13 07:27 UTC by GitOfJason

### Description
This feature implements the highlighting of terms in course articles and a preview of more content when the cursor focuses on terms

<img width="642" alt="image" src="https://user-images.githubusercontent.com/124339951/231684397-fe61f58e-3014-41fb-9599-461d12421ba4.png">

### Remarks
The preview content of terminology currently only supports the use of MDX files, so each terminology should correspond to an MDX file.

**How to use term preview in Course mdx file?**

<img width="796" alt="image" src="https://user-images.githubusercontent.com/124339951/231684947-2acb2389-541d-41a0-8f08-a0ad9b019b16.png">

2023-04-13 13:43 UTC, Flouse commented on src/content/terms/index.ts
> +export const terms: Terms = {
Just an idea:
I think `annotation` may be a better word than `term`
```md
## Example
- critical annotations between the lines
- annotations made in a book
```
## Why
This `keyword annotation` feature is used not only to explain new glossaries and terms, but also to explain some ideas, provide references, etc.

---
Just presenting ideas, if you stick to your wording, LGTM.

2023-04-13 13:53 UTC, Flouse requested changes

2023-04-13 13:53 UTC, Flouse commented on src/content/terms/ckb-vm.mdx
> +- [CKB-VM from RFCS](https://docs.nervos.org/docs/basics/glossary#general-glossary)
```suggestion
- [CKB-VM RFC (Final)](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0003-ckb-vm/0003-ckb-vm.md)
```

2023-04-13 13:59 UTC, Flouse requested changes

2023-04-13 13:59 UTC, Flouse commented on src/content/courses/basic-theory/chapter_1.mdx
> +:term[Cell] is the basic unit of :term[CKB], similar to a cell in the human body. All the cells constitute the general state of the entire CKB blockchain. When we initiate a transaction on the blockc
```suggestion
:term[Cell] is the basic unit of CKB, similar to a cell in the human body. All the cells constitute the general state of the entire CKB blockchain. When we initiate a transaction on the blockchain, thus making a state change, in the end, for CKB, it is nothing more than spending some cells while creating some new ones, no matter how complicated the transaction and the state change are. This process is the same as the [Bitcoin UTXO](https://developer.bitcoin.org/glossary.html?highlight=utxo).
```

2023-04-13 13:59 UTC, Flouse commented on src/content/terms/ckb.mdx
> +All data on Nervos CKB is stored in cells. Cells are the primary state units in CKB, within them users can include arbitrary states.
```suggestion
An abbreviation which can have different meanings depending on the context:
```

2023-04-14 01:45 UTC, RetricSu approved these changes

2023-04-14 02:43 UTC, Flouse approved these changes

2023-04-14 02:43 UTC, merged

2023-06-27 08:27 UTC, Flouse commented
> <img alt="image" width="642" src="https://user-images.githubusercontent.com/124339951/231684397-fe61f58e-3014-41fb-9599-461d12421ba4.png">

The link in the `annotation view` should open a new browser tab by default.